on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Build React app
        run: npm run build --if-present

      - name: upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: FrontendApplication
          path: frontend/dist

  deploy:
    runs-on: [self-hosted, dev]
    needs: build-and-upload

    steps:
      - name: delete old js file
        run: rm -rf /home/ubuntu/frontend/dist

      - name: download js file from artifact
        uses: actions/download-artifact@v3
        with:
          name: FrontendApplication
          path: /home/ubuntu/frontend/dist

      - name: 배포하기
        run: /home/ubuntu/frontend/deploy.sh

      - name: send slack message

        uses: 8398a7/action-slack@v3
        with:
          mention: 'here'
          if_mention: always
          status: ${{ job.status }}
          fields: workflow,job,commit,message,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DEV_DEPLOY_SLACK_WEBHOOK_URL }}
        if: always()
