on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build React app
        run: yarn build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
	
      - name: Build Docker Image and Push DockerHub
        uses: docker/build-push-action@v4
        with:
          context: . # 변경 필요
          file: ./Dockerfile # 변경 필요
          push: true
          platforms: linux/arm64
          tags: gn753/read-a-perfume#:latest

  deploy:
      runs-on: [ self-hosted, dev ]
      needs: build
      steps:
      - name: Deploy Using Docker Image
        run: sh /home/ubuntu/frontend/deploy.sh
