on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: FrontendApplication
          path: frontend/dist

  deploy:
    runs-on: [self-hosted, dev]
    needs: build
    steps:
      - name: Deploy Using Docker Image
        run: sh /home/ubuntu/frontend/deploy.sh
